Repository WildCodeSchool/purple-php-2109-project2-castle, pull requests merged in 2021-11, with the labels that each got.

#3 assets,police and color variable
  public/assets/css/style_desktop.css
  public/assets/images/desktop/Castle_battle_desktop.png
  public/assets/images/desktop/Terms_of_us_sky.png
  public/assets/images/desktop/battle_tent.png
  public/assets/images/desktop/desktop_castle_troop_choice.png
  public/assets/images/desktop/home_castle.png
  public/assets/images/desktop/home_grass.png
  public/assets/images/desktop/home_sky.png
  public/assets/images/desktop/icon-music.png
  public/assets/images/desktop/icon-return.png
  public/assets/images/desktop/path_desktop.png
  public/assets/images/desktop/term_of_us_grass.png
  public/assets/images/desktop/troop_grass.png
  public/assets/images/favicon.png
  public/assets/images/mobile/archer.png
  public/assets/images/mobile/battle_.png
  public/assets/images/mobile/battle_castle.png
  public/assets/images/mobile/bubble.png
  public/assets/images/mobile/grass.png
  public/assets/images/mobile/happy_emoji.png
  public/assets/images/mobile/home_castle.png
  public/assets/images/mobile/knight.png
  public/assets/images/mobile/logo.png
  public/assets/images/mobile/music_icon.png
  public/assets/images/mobile/path.png
  public/assets/images/mobile/pikeman.png
  public/assets/images/mobile/return_icon.png
  public/assets/images/mobile/sad_emoji.png
  public/assets/images/mobile/sky.png
  public/assets/images/mobile/troop_choice_castle.png
Labels: reviewed

#1 create class Trooper
  src/Model/Trooper.php
Labels: reviewed

#5 Us10 home
  public/assets/css/home.css
  public/assets/css/home_tablet_and_desktop.css
  public/assets/css/style.css
  public/assets/css/style_desktop.css
  public/assets/images/desktop/home_background.png
  public/assets/images/desktop/home_castle.png
  public/assets/images/mobile/home_background.png
  public/assets/images/mobile/home_castle.png
  public/assets/images/mobile/question_mark.png
  public/assets/images/tablet/home_background_portrait.png
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: corrections done, Reviewed

#8 Us#3 - New version TermsOfService.html.twig and Tutorial.html.twig
  public/assets/css/tutorialAndTOS.css
  public/assets/images/mobile/roi.png
  public/assets/images/mobile/round.png
  src/Controller/TermsOfServiceController.php
  src/Controller/TutorialController.php
  src/View/Annexes/termsOfService.html.twig
  src/View/Annexes/tutorial.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: corrections done, Reviewed

#10 Locally hosted fonts
  public/assets/css/fonts/LondrinaSolid/LondrinaSolid-Black.ttf
  public/assets/css/fonts/LondrinaSolid/LondrinaSolid-Light.ttf
  public/assets/css/fonts/LondrinaSolid/LondrinaSolid-Regular.ttf
  public/assets/css/fonts/LondrinaSolid/LondrinaSolid-Thin.ttf
  public/assets/css/fonts/Roboto/Roboto-Black.ttf
  public/assets/css/fonts/Roboto/Roboto-BlackItalic.ttf
  public/assets/css/fonts/Roboto/Roboto-Bold.ttf
  public/assets/css/fonts/Roboto/Roboto-BoldItalic.ttf
  public/assets/css/fonts/Roboto/Roboto-Italic.ttf
  public/assets/css/fonts/Roboto/Roboto-Light.ttf
  public/assets/css/fonts/Roboto/Roboto-LightItalic.ttf
  public/assets/css/fonts/Roboto/Roboto-Medium.ttf
  public/assets/css/fonts/Roboto/Roboto-MediumItalic.ttf
  public/assets/css/fonts/Roboto/Roboto-Regular.ttf
  public/assets/css/fonts/Roboto/Roboto-Thin.ttf
  public/assets/css/fonts/Roboto/Roboto-ThinItalic.ttf
  public/assets/css/fonts/Skranji/Skranji-Bold.ttf
  public/assets/css/fonts/Skranji/Skranji-Regular.ttf
  public/assets/css/style.css
Labels: Reviewed

#12 US5 - Views GetReady and Fight
  public/assets/css/get_ready.css
  public/assets/css/get_ready_desktop.css
  src/View/Fight/fight.html.twig
  src/View/Fight/get_ready.html.twig
Labels: corrections done, Reviewed

#14 Us10 home
  public/assets/css/home.css
  public/assets/css/home_tablet_and_desktop.css
  public/assets/images/desktop/home_background.png
  src/View/Home/index.html.twig
Labels: Reviewed

#4 Us5 fight
  database.sql
  public/assets/css/get_ready.css
  public/assets/css/style.css
  public/assets/images/favicon.png
  public/assets/images/mobile/pikeman.png
  public/assets/images/mobile/sky.png
  public/assets/images/mobile/sky2.png
  public/assets/images/mobile/tent-archer.png
  public/assets/images/mobile/tent-knight.png
  public/assets/images/mobile/tent-pikeman.png
  public/assets/images/mobile/tent.png
  public/assets/images/mobile/vigor1-5.png
  public/assets/images/mobile/vigor2-5.png
  public/assets/images/mobile/vigor3-5.png
  public/assets/images/mobile/vigor4-5.png
  public/assets/images/mobile/vigor5-5.png
  public/assets/js/timer.js
  src/Controller/FightController.php
  src/Controller/ItemController.php
  src/Model/CastleManager.php
  src/Model/ItemManager.php
  src/Model/SessionHandler.php
  src/Model/TroopManager.php
  src/Model/Trooper.php
  src/View/Fight/fight.html.twig
  src/View/Fight/get_ready.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_form.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/layout.html.twig
  src/routes.php
Labels: corrections done, Reviewed

#18 ReadMe file Update
  README.md
Labels: Reviewed

#13 Us#3
  public/assets/css/tutorialAndTOS.css
  public/assets/images/mobile/gamepocket.png
  src/Controller/TermsOfServiceController.php
  src/View/Annexes/termsofservice.html.twig
  src/View/Annexes/tutorial.html.twig
  src/routes.php
Labels: corrections done, Reviewed

#19 update database
  database.sql
Labels: Reviewed

#16 US5 - Timer JS
  public/assets/js/timer.js
Labels: corrections done, Reviewed

#20 correction bug in view fight ans get ready
  src/View/Fight/fight.html.twig
  src/View/Fight/get_ready.html.twig
Labels: Reviewed

#21 CSS updated
  public/assets/css/get_ready.css
  public/assets/css/home.css
  public/assets/css/style.css
Labels: Reviewed

#23 create reset button
  public/assets/js/reset.js
  src/Controller/ResetController.php
  src/View/Annexes/termsofservice.html.twig
  src/routes.php
Labels: Reviewed

#24 problems of display fixed
  public/assets/css/tutorialAndTOS.css
  src/View/Annexes/termsofservice.html.twig
  src/View/Annexes/tutorial.html.twig
  src/View/Fight/fight.html.twig
Labels: Reviewed

#26 design reset button
  public/assets/css/tutorialAndTOS.css
  src/View/Annexes/termsofservice.html.twig
Labels: Reviewed

#27 add reset ifbad player
  public/assets/js/reset.js
  src/View/Fight/get_ready.html.twig
Labels: Reviewed

#28 header standardization
  public/assets/css/get_ready.css
  public/assets/css/home.css
  public/assets/css/home_tablet_and_desktop.css
  public/assets/css/style.css
  public/assets/css/tutorialandtos.css
  src/View/Annexes/termsofservice.html.twig
  src/View/Annexes/tutorial.html.twig
  src/View/Fight/fight.html.twig
  src/View/Fight/get_ready.html.twig
  src/View/Home/index.html.twig
Labels: corrections done, Reviewed

#29 Updated SQL request (IF EXISTS inverted)
  database.sql
Labels: Reviewed

#30 Img update
  database.sql
  public/assets/css/get_ready.css
  public/assets/css/get_ready_desktop.css
  public/assets/css/tutorialandtos.css
  public/assets/images/desktop/-archer_tent.png
  public/assets/images/desktop/-knight_tent.png
  public/assets/images/desktop/-pikeman_tent.png
  public/assets/images/mobile/archer.png
  public/assets/images/mobile/knight.png
  public/assets/images/mobile/pikeman.png
  public/assets/images/mobile/vigor0-5.png
  public/assets/images/mobile/vigor1-5.png
  public/assets/images/mobile/vigor2-5.png
  public/assets/images/mobile/vigor3-5.png
  public/assets/images/mobile/vigor4-5.png
  public/assets/images/mobile/vigor5-5.png
  src/Controller/AdminController.php
  src/Controller/FightController.php
  src/Controller/HomeController.php
  src/Model/AdminManager.php
  src/Model/SessionHandler.php
  src/Model/Trooper.php
  src/View/Admin/password.html.twig
  src/View/Annexes/termsofservice.html.twig
  src/View/Fight/fight.html.twig
  src/View/Fight/get_ready.html.twig
  src/View/Home/index.html.twig
  src/routes.php
Labels: Reviewed

#32 Sql update
  database.sql
Labels: corrections done, Reviewed

#37 bugs fixed according to W3C validator on tutorial.html.twig and terms…
  public/assets/css/tutorialandtos.css
  src/View/Annexes/termsofservice.html.twig
  src/View/Annexes/tutorial.html.twig
Labels: corrections done, Reviewed

#34 Views update
  database.sql
  public/assets/images/desktop/-tent-archer.png
  public/assets/images/desktop/-tent-knight.png
  public/assets/images/desktop/-tent-pikeman.png
  src/Model/Trooper.php
  src/View/Fight/fight.html.twig
  src/View/Fight/get_ready.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#36 Js update
  database.sql
  public/assets/js/timer.js
Labels: Reviewed

#44 correctif issus button rests and page admin
  public/assets/css/tutorialandtos.css
Labels: Reviewed

#45 bug fixed according to issue spelling errors
  src/View/Annexes/termsofservice.html.twig
  src/View/Annexes/tutorial.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#46 update admin
  src/View/Admin/password.html.twig
Labels: 2 rewiews done

#48 cryptage password
  database.sql
  src/Controller/AdminController.php
  src/Model/AdminManager.php
  src/View/Admin/firstpassword.html.twig
  src/routes.php
Labels: Reviewed, HELP Romain :), 2 rewiews done

#50 desktop emoji position updated
  public/assets/css/get_ready_desktop.css
Labels: Reviewed, 2 rewiews done

#51 display bug fixed
  public/assets/css/home.css
  src/View/Home/index.html.twig
Labels: 2 rewiews done

#52 coreectif faille security
  src/Controller/AdminController.php
  src/View/Fight/fight.html.twig
Labels: corrections done, Reviewed, HELP Romain :), 2 rewiews done, end of project \0/

#53 correctif W3C
  src/View/Admin/firstpassword.html.twig
  src/View/Admin/password.html.twig
Labels: Reviewed, HELP Romain :), 2 rewiews done, end of project \0/

#54 Fix for CD
  migration.php
  nginx.conf
  src/routing.php
Labels: Reviewed, 2 rewiews done, end of project \0/

#55 log out admin link fixed
  src/View/Home/index.html.twig
Labels: Reviewed, 2 rewiews done, end of project \0/
